Methods of Machine Learning and Intellectual Analysis of Data (Learning course) \
Bohdan Pavlyshenko (https://www.linkedin.com/in/bpavlyshenko/) \
Youtube video: https://www.youtube.com/watch?v=m9iUiBKCxVM&list=PLMQt7tnruMvF1jetHNUKjMtHKSp78H2bb&index=4

# Classification

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, cross_val_score,  cross_val_predict
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, \
log_loss, recall_score, precision_score
from sklearn.model_selection import GridSearchCV
sns.set_style("whitegrid")
%matplotlib inline

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')
#path_drive = '/content/drive/MyDrive/Colab Notebooks/ml_course/'
#df = pd.read_csv(path_drive + 'data/data_iris.csv')

In [ ]:
df=pd.read_csv('data/data_iris.csv')
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                4.9               3.6                1.4               0.1   
1                5.6               2.9                3.6               1.3   
2                6.6               2.9                4.6               1.3   
3                5.7               2.8                4.1               1.3   
4                6.6               3.0                4.4               1.4   

   target  
0       0  
1       1  
2       1  
3       1  
4       1

In [ ]:
features = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)']

In [ ]:
X=df[features].values
y=df.target.values
X_train, X_test, y_train, y_test = train_test_split( X,y, test_size=0.3, random_state=11)

In [ ]:
clf = RandomForestClassifier(n_estimators=100)
_=clf.fit(X_train,y_train)

In [ ]:
pred=clf.predict(X_test)

In [ ]:
confusion_matrix(y_test,pred)

array([[17,  0,  0],
       [ 0, 12,  1],
       [ 0,  2, 13]])

In [ ]:
classf_report=classification_report(y_test, pred)
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.86      0.92      0.89        13
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [ ]:
pred

array([1, 0, 2, 0, 1, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1,
       0, 2, 1, 2, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 2, 2, 0, 0, 2, 1, 0, 1,
       0])

In [ ]:
pred_proba=clf.predict_proba(X_test)

In [ ]:
pred_proba[0:7]

array([[0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.05, 0.95],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ]])

In [ ]:
pred=np.zeros(X.shape[0])
pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
y

array([0, 1, 1, 1, 1, 0, 0, 2, 0, 2, 0, 2, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1,
       0, 2, 2, 0, 1, 2, 0, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 0, 2, 0, 1,
       1, 0, 2, 1, 2, 1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 0,
       2, 1, 1, 0, 0, 0, 2, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0,
       1, 0, 2, 2, 2, 2, 2, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 2, 0, 0,
       1, 1, 1, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 2, 1, 1, 2, 2, 1, 1,
       0, 1, 2, 1, 1, 2, 0, 0, 2, 0, 0, 2, 0, 0, 1, 2, 1, 1])

In [ ]:
kf = KFold(n_splits=5, shuffle=True, random_state=10)
for i, (train_index, test_index) in enumerate(kf.split(X)):
    clf = RandomForestClassifier(n_estimators=100)
    print (f'\nFold {i}')
    clf.fit(X[train_index,:], y[train_index])
    pred[test_index]= clf.predict(X[test_index,:])


Fold 0

Fold 1

Fold 2

Fold 3

Fold 4


In [1]:
print(classification_report(y, pred))

NameError: name 'classification_report' is not defined

In [ ]:
confusion_matrix(y,pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [ ]:
kf = KFold(n_splits = 5, shuffle = True,  random_state = 10)
clf = RandomForestClassifier(n_estimators=100)
pred = cross_val_predict(clf, X, y, cv = kf, method = 'predict')
df['pred']=pred

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                4.9               3.6                1.4               0.1   
1                5.6               2.9                3.6               1.3   
2                6.6               2.9                4.6               1.3   
3                5.7               2.8                4.1               1.3   
4                6.6               3.0                4.4               1.4   

   target  pred  
0       0     0  
1       1     1  
2       1     1  
3       1     1  
4       1     1

In [ ]:
pred = cross_val_predict(clf, X, y, cv = kf, method = 'predict')

In [ ]:
pred_proba = cross_val_predict(clf, X, y, cv = kf, method = 'predict_proba')

In [ ]:
pred_proba[:10]

array([[1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.99, 0.  , 0.01],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.99, 0.01, 0.  ],
       [0.  , 0.01, 0.99]])

In [ ]:
acc_score = accuracy_score(df['target'], df['pred'])
acc_score

0.96

In [ ]:
classf_report=classification_report(df['target'], df['pred'])
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.94      0.94        50
           2       0.94      0.94      0.94        50

    accuracy                           0.96       150
   macro avg       0.96      0.96      0.96       150
weighted avg       0.96      0.96      0.96       150



In [ ]:
confusion_matrix(df['target'], df['pred'])

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]])

In [ ]:
f1_score(df['target'], df['pred'], average='micro'), f1_score(df['target'], df['pred'], average='macro')

(0.96, 0.96)

In [ ]:
df['pred']

0      0
1      1
2      1
3      1
4      1
      ..
145    0
146    1
147    2
148    1
149    1
Name: pred, Length: 150, dtype: int64

In [ ]:
df['target']

0      0
1      1
2      1
3      1
4      1
      ..
145    0
146    1
147    2
148    1
149    1
Name: target, Length: 150, dtype: int64

In [ ]:
log_loss(df['target'].values, pred_proba)

0.10380815301831287

In [ ]:
recall_score(df['target'], df['pred'], average='macro')

0.96

In [ ]:
precision_score(df['target'], df['pred'], average='macro')

0.96

In [ ]:
clf = GaussianNB()
_=clf.fit(X_train,y_train)
pred=clf.predict(X_test)
classf_report=classification_report(y_test, pred)
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.86      0.92      0.89        13
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [ ]:
clf = svm.SVC()
_=clf.fit(X_train,y_train)
pred=clf.predict(X_test)
classf_report=classification_report(y_test, pred)
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.87      1.00      0.93        13
           2       1.00      0.87      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45



In [ ]:
kf = KFold(n_splits = 5, shuffle = True,  random_state = 10)
clf = svm.SVC()
pred = cross_val_predict(clf, X, y, cv = kf, method = 'predict')
classf_report=classification_report(df['target'].values, pred)
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       0.94      0.96      0.95        50
           2       0.96      0.94      0.95        50

    accuracy                           0.97       150
   macro avg       0.97      0.97      0.97       150
weighted avg       0.97      0.97      0.97       150



In [ ]:
clf = KNeighborsClassifier(n_neighbors=3)
_=clf.fit(X_train,y_train)
pred=clf.predict(X_test)
classf_report=classification_report(y_test, pred)
print(classf_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       0.93      1.00      0.96        13
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [ ]:
parameters = {'n_neighbors':[1,3,5,7]}
knn=KNeighborsClassifier()
clf = GridSearchCV(knn, param_grid=parameters,
                      scoring='accuracy',
                      cv=7)
_=clf.fit(X_train,y_train)
clf.best_params_

{'n_neighbors': 3}