In [1]:
import numpy as np
import random
from math import sqrt
from random import randint
import math

In [2]:
A = []
n = 7
A = np.random.randint(4, 8, (n, n))

In [3]:
print(A)

[[7 5 4 5 5 7 7]
 [5 7 5 7 5 4 4]
 [5 6 7 6 4 7 4]
 [4 6 5 4 5 6 5]
 [7 7 5 5 7 4 7]
 [6 4 6 6 4 7 6]
 [4 6 5 6 5 6 7]]


In [4]:
n = 100
scale = 2.5
a = 4
b = 8

In [5]:
B = np.zeros(n + 1, dtype=np.longdouble)
X0 = np.zeros(n + 1, dtype=np.longdouble)
X1 = np.zeros(n + 1, dtype=np.longdouble)
A = np.zeros((n + 1, n + 1), dtype=np.longdouble)

In [6]:
def norma_vector_diff(Y, X, n):
    max_diff = 0
    for i in range(1, n + 1):
        diff = abs(Y[i] - X[i])
        if diff > max_diff:
            max_diff = diff
    return max_diff

In [7]:
def norma_matrix(X, n):
    max_sum = 0
    for i in range(1, n + 1):
        row_sum = sum(abs(X[i][j]) for j in range(1, n + 1))
        if row_sum > max_sum:
            max_sum = row_sum
    return max_sum


In [8]:
def Method_Zeidelya(A, B, X0, X1, n, k):
    kmax = int(1e5)
    eps = 1e-14
    print("\nМетод Зейделя\n\n")
    k[0] = 1
    while True:
        for i in range(1, n + 1):
            X0[i] = X1[i]
        for i in range(1, n + 1):
            sum = 0.0
            for j in range(1, n + 1):
                if j < i:
                    sum += A[i][j] * X1[j]
                elif j > i:
                    sum += A[i][j] * X0[j]
            X1[i] = (B[i] - sum) / A[i][i]
        k[0] += 1
        if k[0] > kmax or norma_vector_diff(X1, X0, n) < eps:
            break
    if k[0] >= kmax:
        print("Рішення не знайдено!\n")
    else:
        print(f"Рішення знайдено!\n")
        print("Ітерація:", k[0])

In [9]:
def Method_Jacobi(A, B, X0, X1, n, k):
    kmax = int(1e5)
    eps = 1e-14
    print("\nМетод Якобі\n\n")
    k[0] = 1
    while True:
        for i in range(1, n + 1):
            X0[i] = X1[i]
        for i in range(1, n + 1):
            sum = 0.0
            for j in range(1, n + 1):
                if j != i:
                    sum += A[i][j] * X0[j]
            X1[i] = (B[i] - sum) / A[i][i]
        k[0] += 1
        if k[0] > kmax or norma_vector_diff(X1, X0, n) < eps:
            break
    if k[0] >= kmax:
        print("Рішення не знайдено!\n")
    else:
        print("Рішення знайдено!\n")
        print("Ітерація:", k[0])

In [10]:
def Method_Simple_iteration(A, B, X0, X1, n, k, tau):
    kmax = int(1e5)
    eps = 1e-14
    print("\nМетод простої ітерації\n\n")
    k[0] = 1
    while True:
        for i in range(1, n + 1):
            X0[i] = X1[i]
        for i in range(1, n + 1):
            suma = sum(X0[j] * A[i][j] for j in range(1, n + 1))
            X1[i] = X0[i] - tau * suma + tau * B[i]
        k[0] += 1
        if k[0] > kmax or norma_vector_diff(X1, X0, n) < eps:
            break
    if k[0] >= kmax:
        print("Рішення не знайдено!\n")
    else:
        print("Рішення знайдено!\n")
        print("Ітерація:", k[0])

In [11]:
for i in range(1, n + 1):
    suma = 0
    for j in range(1, n + 1):
        A[i][j] = randint(a, b)
        if i != j:
            suma += A[i][j]
    A[i][i] = suma * scale


In [12]:
with open("matrix_A.txt", "w") as matrix_A:
    for i in range(1, n + 1):
        for j in range(1, n):
            matrix_A.write(f"{A[i][j]:.6e}\t")
        matrix_A.write(f"{A[i][n]:.6e}\n")


In [13]:
with open("matrix_A.txt", "r") as matrix_A:
    for i in range(1, n + 1):
        line = matrix_A.readline().strip().split()
        for j in range(1, n + 1):
            A[i][j] = np.longdouble(line[j - 1])

In [14]:
with open("matrix_B.txt", "w") as matrix_B:
    x = 2.51
    for i in range(1, n + 1):
        B[i] = sum(A[i][j] for j in range(1, n + 1)) * x
        matrix_B.write(f"{B[i]:.15}\n")

In [15]:
norma_vector_diff(X1, X0, n)

0

In [16]:
norma_matrix(A, n)

2208.5

In [17]:
with open("matrix_XI.txt", "w") as matrix_XI:
    tau = 1 / norma_matrix(A, n)
    k = [1]

    Method_Simple_iteration(A, B, X0, X1, n, k, tau)
    for i in range(1, n + 1):
        matrix_XI.write(f"{X1[i]:.3}\n")

    SI = f"SI\t{k[0]}\n"


Метод простої ітерації


Рішення знайдено!

Ітерація: 34


In [18]:
with open("matrix_XY.txt", "w") as matrix_XY:

    k[0] = 1
    Method_Jacobi(A, B, X0, X1, n, k)
    for i in range(1, n + 1):
        matrix_XY.write(f"{X1[i]:.15}\n")
    YA = f"Ya\t{k[0]}\n"


Метод Якобі


Рішення знайдено!

Ітерація: 2


In [19]:
with open("matrix_XG.txt", "w") as matrix_XG:
    k[0] = 1
    Method_Zeidelya(A, B, X0, X1, n, k)
    for i in range(1, n + 1):
        matrix_XG.write(f"{X1[i]:.15}\n")
    GZ = f"GZ\t{k[0]}\n"



Метод Зейделя


Рішення знайдено!

Ітерація: 2


In [20]:
with open("output.txt", "w") as output:
    output.write(SI)
    output.write(YA)
    output.write(GZ)