In [1]:
import random
import numpy as np
from math import sqrt

In [2]:
A = []
n = 5
A = np.random.randint(4, 8, (n, n))

In [3]:
print(A)

[[5 6 5 6 5]
 [7 6 6 7 7]
 [6 4 7 7 5]
 [7 7 4 6 5]
 [4 5 6 7 4]]


In [4]:
X = np.full((n, 1), 2)

In [5]:
print("Розв'язок системи рівнянь: \n",X)

Розв'язок системи рівнянь: 
 [[2]
 [2]
 [2]
 [2]
 [2]]


In [6]:
def find_vector_B(A, X):
    n = A.shape[0]
    B = np.zeros((n, 1))
    for i in range(n):
        for j in range(n):
            B[i] += A[i, j] * X[j]
    return B

In [7]:
B = find_vector_B(A,X)
print("Вектор B: \n" , B)

Вектор B: 
 [[54.]
 [66.]
 [58.]
 [58.]
 [52.]]


In [8]:
def LU_ROZKLAD(A):
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Заповнення верхньої трикутної матриці U
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))

        # Заповнення нижньої трикутної матриці L
        L[i, i] = 1
        for k in range(i + 1, n):
            L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]

    return L, U

In [9]:
L , U = LU_ROZKLAD(A)

In [10]:
print("L = \n",L)

L = 
 [[ 1.          0.          0.          0.          0.        ]
 [ 1.4         1.          0.          0.          0.        ]
 [ 1.2         1.33333333  1.          0.          0.        ]
 [ 1.4         0.58333333 -1.03571429  1.          0.        ]
 [ 0.8        -0.08333333  0.82142857  5.          1.        ]]


In [11]:
print("U = \n",U)

U = 
 [[ 5.          6.          5.          6.          5.        ]
 [ 0.         -2.4        -1.         -1.4         0.        ]
 [ 0.          0.          2.33333333  1.66666667 -1.        ]
 [ 0.          0.          0.          0.14285714 -3.03571429]
 [ 0.          0.          0.          0.         16.        ]]


In [12]:
def matrix_vector_dobutok(A, X):
    n, m = A.shape
    result = np.zeros((n, 1))
    for i in range(n):
        for j in range(m):
            result[i] += A[i, j] * X[j]

    return result

In [13]:
dobutok = matrix_vector_dobutok(A,X)
print("Добуток матриці та вектора: \n" ,dobutok)

Добуток матриці та вектора: 
 [[54.]
 [66.]
 [58.]
 [58.]
 [52.]]


In [14]:
def norm_vector(vector):
  norma = 0
  for i in range(n):
    norma += pow(X[i],2)
  return sqrt(norma[0])

In [15]:
print("Норма вектора: ",norm_vector(X))

Норма вектора:  4.47213595499958


In [16]:
def eps_axb(A, x, b):
    n = len(b)
    max_residual = 0

    for i in range(n):
        residual_i = abs(sum(A[i][j] * x[j] for j in range(n)) - b[i])
        max_residual = max(max_residual, residual_i)

    return max_residual

In [17]:
eps = eps_axb(A,X,B)
print('Похибка точності:' , eps)

Похибка точності: 0
